name: MBDS Pizza Local
values:
  - key: baseUrl
    value: http://localhost:8080
    enabled: true
  - key: adminPhone
    value: "+261000000000"
    enabled: true
  - key: adminPassword
    value: "1234"
    enabled: true
  - key: token
    value: ""
    enabled: true
  - key: ingredientId
    value: ""
    enabled: true
  - key: pizzaId
    value: ""
    enabled: true
color: null
