spring.application.name=wsrest
springdoc.swagger-ui.path=/swagger-ui.html

spring.profiles.active=h2

server.forward-headers-strategy=framework

spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true