name: Deploy Latest Image to VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ghcr.io/mbds-ws/mbds-pizza:latest
            docker stop pizza-api || true
            docker rm pizza-api || true
            docker run -d --pull always -p 8080:8080 --restart unless-stopped --name pizza-api ghcr.io/mbds-ws/mbds-pizza:latest
            docker image prune -f
